export const routes = {
  registry: "/registry",
  login: "/login",
  dashboard: "/dashboard",
  usuarios: "/dashboard/usuarios",
  usuarioDetail: (id: string) => `/dashboard/usuarios/${id}`,
  clases: "/dashboard/clases",
  reservas: "/dashboard/reservas",
  pagos: "/dashboard/pagos",
  suscripciones: "/dashboard/suscripciones",
  planes: "/dashboard/planes",
  cupones: "/dashboard/cupones",
  coaches: "/dashboard/coaches",
  coachAttendance: "/dashboard/coaches/attendance",
  coachSchedule: "/dashboard/coaches/schedule",
  reportes: "/dashboard/reportes",
  politica: "/dashboard/politica",
  configuracion: "/dashboard/configuracion",
  calendario: "/dashboard/calendario",
  devoluciones: "/dashboard/devoluciones",
  historico: "/dashboard/historico",
} as const
